Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define "mysqldb" do |mysql|
  mysql.vm.network "public_network", ip: "192.168.56.4"

  mysql.vm.hostname = "ubunto.vagrant"
  mysql.vm.provision "shell", inline: $script_mysql
  mysql.vm.provision "shell",
	inline: "service mysql restart"

    end
#  config.vm.synced_folder "~/alura/", "/configs"

    config.vm.define "phpweb" do |phpweb|
	phpweb.vm.network "forwarded_port", guest:80, host:8089
	phpweb.vm.network "public_network", ip: "192.168.56.25"
    end
end
